sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dhomane/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dhomane/docker-react npm run test